package gold.debug.windowstolinux.shared.standard.analyze.ecosystem.python;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import gold.debug.windowstolinux.shared.model.project.DeploymentBuildToolType;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class PythonBuildInspectorTest {
    @org.junit.jupiter.api.Test
    void acceptsRealMultilineHashLocksAndRejectsAnUnhashedDependency() throws Exception {
        Path directory = java.nio.file.Files.createTempDirectory("pip-lock-test");
        try {
            var inspector = new gold.debug.windowstolinux.shared.standard.analyze.ecosystem.python.pip.PipBuildInspector();
            String lock = "jsonschema==4.26.0 \\\n    --hash=sha256:" + "a".repeat(64) + " \\\n    --hash=sha256:"
                    + "b".repeat(64) + "\n# via fixture\n";
            for (String newline : List.of("\n", "\r\n")) {
                java.nio.file.Files.writeString(directory.resolve("requirements.lock"), lock.replace("\n", newline));
                org.junit.jupiter.api.Assertions.assertTrue(inspector.inspect(directory).isPresent());
            }
            java.nio.file.Files.writeString(directory.resolve("requirements.lock"), lock + "unhashed==1.0\n");
            org.junit.jupiter.api.Assertions.assertTrue(inspector.inspect(directory).isEmpty());
        } finally {
            java.nio.file.Files.deleteIfExists(directory.resolve("requirements.lock"));
            java.nio.file.Files.delete(directory);
        }
    }
    @TempDir
    Path temporaryDirectory;

    @Test
    void preservesTheReviewedOrderOfNamedDependencyArchitectures() throws Exception {
        Files.writeString(temporaryDirectory.resolve("pyproject.toml"), "[project]\nname = \"demo\"\n");
        Files.writeString(temporaryDirectory.resolve("Pipfile"), pipfile());
        lockFiles().forEach((lockFile, content) -> write(temporaryDirectory.resolve(lockFile), content));

        PythonBuildFacts facts = new PythonBuildInspector().inspect(temporaryDirectory).orElseThrow();

        assertEquals(List.of("requirements.lock", "Pipfile.lock", "poetry.lock", "uv.lock"), facts.lockFiles());
    }

    @Test
    void selectsEachNamedDependencyArchitectureFromItsLockfile() throws Exception {
        Map<String, DeploymentBuildToolType> architectures = new LinkedHashMap<>();
        architectures.put("requirements.lock", DeploymentBuildToolType.PIP_LOCKED);
        architectures.put("Pipfile.lock", DeploymentBuildToolType.PIPENV_LOCKED);
        architectures.put("poetry.lock", DeploymentBuildToolType.POETRY_LOCKED);
        architectures.put("uv.lock", DeploymentBuildToolType.UV_LOCKED);

        int index = 0;
        for (Map.Entry<String, DeploymentBuildToolType> architecture : architectures.entrySet()) {
            Path root = Files.createDirectory(temporaryDirectory.resolve("architecture-" + index++));
            Files.writeString(root.resolve("pyproject.toml"), "[project]\nname = \"demo\"\n");
            if (architecture.getKey().equals("Pipfile.lock")) {
                Files.writeString(root.resolve("Pipfile"), pipfile());
            }
            Files.writeString(root.resolve(architecture.getKey()), lockFiles().get(architecture.getKey()));
            PythonBuildFacts facts = new PythonBuildInspector().inspect(root).orElseThrow();
            assertEquals(architecture.getValue(), facts.buildTool());
            assertEquals(List.of(architecture.getKey()), facts.lockFiles());
        }
    }

    @Test
    void refusesUnhashedPipAndMalformedToolLocksBeforePlanning() throws Exception {
        Files.writeString(temporaryDirectory.resolve("pyproject.toml"), "[project]\nname = \"demo\"\n");
        Files.writeString(temporaryDirectory.resolve("Pipfile"), pipfile());
        for (String lockFile : List.of("requirements.lock", "Pipfile.lock", "poetry.lock", "uv.lock")) {
            Files.writeString(temporaryDirectory.resolve(lockFile), "dependency==1.0\n");
        }

        assertTrue(new PythonBuildInspector().inspect(temporaryDirectory).orElseThrow().lockFiles().isEmpty());
    }

    private static Map<String, String> lockFiles() {
        Map<String, String> locks = new LinkedHashMap<>();
        locks.put("requirements.lock", "# Zero external dependencies.\n");
        locks.put("Pipfile.lock",
                "{\"_meta\":{\"requires\":{\"python_version\":\"3.12\"}}," + "\"default\":{},\"develop\":{}}\n");
        locks.put("poetry.lock",
                "# This file is automatically @generated by Poetry and should not be changed by hand.\n"
                        + "package = []\n\n[metadata]\nlock-version = \"2.1\"\npython-versions = \"==3.12.*\"\n"
                        + "content-hash = \"" + "0".repeat(64) + "\"\n");
        locks.put("uv.lock", "version = 1\nrevision = 1\nrequires-python = \"==3.12.*\"\n\n"
                + "[[package]]\nname = \"demo\"\nversion = \"0.1.0\"\nsource = { virtual = \".\" }\n");
        return locks;
    }

    private static String pipfile() {
        return "[packages]\n\n[dev-packages]\n\n[requires]\npython_version = \"3.12\"\n";
    }

    private static void write(Path path, String content) {
        try {
            Files.writeString(path, content);
        } catch (java.io.IOException error) {
            throw new java.io.UncheckedIOException(error);
        }
    }
}
