<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>gold.debug.windowstolinux</groupId>
    <artifactId>windowstolinux-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>WindowsToLinux Parent</name>
    <description>WindowsToLinux multi-module build root</description>

    <modules>
        <module>src/shared</module>
        <module>src/app</module>
        <module>src/web</module>
    </modules>

    <properties>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <junit.version>5.11.4</junit.version>
        <maven.compiler.version>3.13.0</maven.compiler.version>
        <maven.enforcer.version>3.5.0</maven.enforcer.version>
        <maven.jar.version>3.4.2</maven.jar.version>
        <maven.surefire.version>3.5.2</maven.surefire.version>
        <maven.resolver.util.version>1.4.1</maven.resolver.util.version>
        <plexus.utils.version>4.0.1</plexus.utils.version>
        <plexus.xml.version>3.0.0</plexus.xml.version>
        <commons.lang3.version>3.14.0</commons.lang3.version>
        <commons.codec.version>1.17.0</commons.codec.version>
        <commons.io.version>2.16.1</commons.io.version>
        <beanshell.version>2.0b6</beanshell.version>
        <zstd-jni.version>1.5.5-11</zstd-jni.version>
        <sshd.version>2.14.0</sshd.version>
        <slf4j.version>1.7.36</slf4j.version>
        <sqlite.version>3.46.0.0</sqlite.version>
        <bouncycastle.version>1.78.1</bouncycastle.version>
        <flatlaf.version>3.7.1</flatlaf.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven.compiler.version}</version>
                    <configuration>
                        <release>${maven.compiler.release}</release>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${maven.jar.version}</version>
                    <dependencies>
                        <dependency>
                            <groupId>com.github.luben</groupId>
                            <artifactId>zstd-jni</artifactId>
                            <version>${zstd-jni.version}</version>
                        </dependency>
                    </dependencies>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven.surefire.version}</version>
                    <configuration>
                        <useModulePath>false</useModulePath>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>${maven.enforcer.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.plexus</groupId>
                        <artifactId>plexus-utils</artifactId>
                        <version>${plexus.utils.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.codehaus.plexus</groupId>
                        <artifactId>plexus-xml</artifactId>
                        <version>${plexus.xml.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.maven.enforcer</groupId>
                        <artifactId>enforcer-api</artifactId>
                        <version>${maven.enforcer.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.maven.enforcer</groupId>
                        <artifactId>enforcer-rules</artifactId>
                        <version>${maven.enforcer.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.maven.resolver</groupId>
                        <artifactId>maven-resolver-util</artifactId>
                        <version>${maven.resolver.util.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.commons</groupId>
                        <artifactId>commons-lang3</artifactId>
                        <version>${commons.lang3.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>commons-codec</groupId>
                        <artifactId>commons-codec</artifactId>
                        <version>${commons.codec.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>commons-io</groupId>
                        <artifactId>commons-io</artifactId>
                        <version>${commons.io.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache-extras.beanshell</groupId>
                        <artifactId>bsh</artifactId>
                        <version>${beanshell.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>require-java-21</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireJavaVersion>
                                    <version>[21,22)</version>
                                    <message>WindowsToLinux must be built with JDK 21.</message>
                                </requireJavaVersion>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
