package gold.debug.windowstolinux.shared.analyze.ecosystem.python.poetry;

import gold.debug.windowstolinux.shared.analyze.source.BoundedMetadataInspector;

import java.io.IOException;
import java.nio.file.Path;
import java.util.Optional;

/**
 * Inspects the Poetry lockfile architecture. / 检查 Poetry 锁文件架构。
 */
public final class PoetryBuildInspector {
    /**
     * Returns Poetry facts when poetry.lock exists. / 在 poetry.lock 存在时返回 Poetry 事实。
     *
     * @param root root directory defining the filesystem boundary / 定义文件系统边界的根目录
     * @return matching result, or empty when no admitted value exists / 匹配结果；不存在已准入内容时为空
     * @throws IOException if the required file or stream operation fails / 所需文件或流操作失败时
     */
    public Optional<String> inspect(Path root) throws IOException {
        String lockFile = "poetry.lock";
        Path path = root.resolve(lockFile);
        if (!BoundedMetadataInspector.regular(path)) return Optional.empty();
        String content = BoundedMetadataInspector.read(path);
        boolean shape = content.startsWith("# This file is automatically @generated by Poetry")
                && content.contains("[metadata]")
                && content.matches("(?s).*lock-version\\s*=\\s*\\\"2\\.1\\\".*")
                && content.matches("(?s).*content-hash\\s*=\\s*\\\"[0-9a-fA-F]{64}\\\".*");
        return shape ? Optional.of(lockFile) : Optional.empty();
    }
}
