package gold.debug.windowstolinux.app.main.startup;

import gold.debug.windowstolinux.shared.model.project.DeploymentProjectType;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;

/** Creates bounded source projects used by ecosystem-service live acceptance. / 创建生态服务实时验收使用的有界源码项目。 */
final class EcosystemServiceAcceptanceFixture {
    private EcosystemServiceAcceptanceFixture() { }

    static Path create(Path parent, DeploymentProjectType projectType, String applicationId, String version,
                       String marker, boolean healthy, Path gradleWrapperJar) throws IOException {
        Path root = Files.createDirectories(parent.resolve(applicationId));
        switch (projectType) {
            case GO_SERVICE -> go(root, version, marker, healthy);
            case RUST_SERVICE -> rust(root, version, marker, healthy);
            case DOTNET_SERVICE -> dotnet(root, version, marker, healthy);
            case KOTLIN_SERVICE -> kotlin(root, marker, healthy, gradleWrapperJar);
            case PHP_SERVICE -> php(root, version, marker, healthy);
            case RUBY_SERVICE -> ruby(root, version, marker, healthy);
            default -> throw new IllegalArgumentException("fixture requires an ecosystem service project type");
        }
        return root;
    }

    private static void go(Path root, String version, String marker, boolean healthy) throws IOException {
        write(root.resolve("go.mod"), "module example.com/windowstolinux/acceptance\n\ngo " + version + "\n");
        write(root.resolve("go.sum"), "");
        write(root.resolve("main.go"), healthy ? """
                package main

                import (
                    "fmt"
                    "net/http"
                    "os"
                )

                func main() {
                    http.HandleFunc("/", func(response http.ResponseWriter, request *http.Request) {
                        _, _ = fmt.Fprint(response, "%s")
                    })
                    if err := http.ListenAndServe("0.0.0.0:"+os.Getenv("PORT"), nil); err != nil {
                        panic(err)
                    }
                }
                """.formatted(marker) : "package main\nimport \"os\"\nfunc main() { os.Exit(36) }\n");
    }

    private static void rust(Path root, String version, String marker, boolean healthy) throws IOException {
        write(root.resolve("Cargo.toml"), """
                [package]
                name = "w2l_rust"
                version = "0.1.0"
                edition = "2021"
                """);
        write(root.resolve("Cargo.lock"), """
                # This file is automatically @generated by Cargo.
                # It is not intended for manual editing.
                version = 3

                [[package]]
                name = "w2l_rust"
                version = "0.1.0"
                """);
        write(root.resolve("rust-toolchain.toml"), """
                [toolchain]
                channel = "%s"
                profile = "minimal"
                """.formatted(version));
        write(root.resolve("src/main.rs"), healthy ? """
                use std::env;
                use std::io::{Read, Write};
                use std::net::TcpListener;

                fn main() {
                    let listener = TcpListener::bind(format!("0.0.0.0:{}", env::var("PORT").unwrap())).unwrap();
                    for stream in listener.incoming() {
                        let mut stream = stream.unwrap();
                        let mut request = [0_u8; 1024];
                        let _ = stream.read(&mut request);
                        let body = "%s";
                        let response = format!("HTTP/1.1 200 OK\\r\\nContent-Length: {}\\r\\nConnection: close\\r\\n\\r\\n{}", body.len(), body);
                        stream.write_all(response.as_bytes()).unwrap();
                    }
                }
                """.formatted(marker) : "fn main() { std::process::exit(36); }\n");
    }

    private static void dotnet(Path root, String version, String marker, boolean healthy) throws IOException {
        String major = version.substring(0, version.indexOf('.'));
        write(root.resolve("global.json"), """
                {
                  "sdk": {
                    "version": "%s",
                    "rollForward": "disable",
                    "allowPrerelease": false
                  }
                }
                """.formatted(version));
        write(root.resolve("W2lDotnet.csproj"), """
                <Project Sdk="Microsoft.NET.Sdk.Web">
                  <PropertyGroup>
                    <TargetFramework>net%s.0</TargetFramework>
                    <Nullable>enable</Nullable>
                    <ImplicitUsings>enable</ImplicitUsings>
                    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
                  </PropertyGroup>
                </Project>
                """.formatted(major));
        write(root.resolve("packages.lock.json"), """
                {
                  "version": 1,
                  "dependencies": {
                    "net%s.0": {}
                  }
                }
                """.formatted(major));
        write(root.resolve("NuGet.Config"), """
                <?xml version="1.0" encoding="utf-8"?>
                <configuration>
                  <packageSources>
                    <clear />
                  </packageSources>
                  <auditSources>
                    <clear />
                  </auditSources>
                </configuration>
                """);
        write(root.resolve("Program.cs"), healthy ? """
                var builder = WebApplication.CreateBuilder(args);
                var app = builder.Build();
                app.MapGet("/", () => "%s");
                app.Run("http://0.0.0.0:" + Environment.GetEnvironmentVariable("PORT"));
                """.formatted(marker) : "Environment.Exit(36);\n");
    }

    private static void kotlin(Path root, String marker, boolean healthy, Path wrapperJar) throws IOException {
        if (wrapperJar == null || !Files.isRegularFile(wrapperJar)) {
            throw new IOException("managed.gradle.wrapper.jar must identify a real verified Gradle wrapper JAR");
        }
        write(root.resolve("settings.gradle.kts"), """
                pluginManagement { repositories { gradlePluginPortal(); mavenCentral() } }
                dependencyResolutionManagement { repositories { mavenCentral() } }
                rootProject.name = "w2l-kotlin"
                """);
        write(root.resolve("build.gradle.kts"), """
                plugins {
                    application
                    kotlin("jvm") version "2.0.21"
                }
                kotlin { jvmToolchain(21) }
                application { mainClass.set("acceptance.MainKt") }
                dependencyLocking { lockAllConfigurations() }
                """);
        write(root.resolve("gradle.lockfile"), """
                # This is a Gradle generated file for dependency locking.
                # Manual edits can break the build and are not advised.
                # This file is expected to be part of source control.
                org.jetbrains:annotations:13.0=compileClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
                org.jetbrains.kotlin:kotlin-stdlib:2.0.21=compileClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
                empty=
                """);
        write(root.resolve("gradlew"), """
                #!/bin/sh
                APP_HOME=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
                exec java -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"
                """);
        write(root.resolve("gradle/wrapper/gradle-wrapper.properties"), """
                distributionBase=GRADLE_USER_HOME
                distributionPath=wrapper/dists
                distributionSha256Sum=31c55713e40233a8303827ceb42ca48a47267a0ad4bab9177123121e71524c26
                distributionUrl=https\\://downloads.gradle.org/distributions/gradle-8.10.2-bin.zip
                networkTimeout=30000
                validateDistributionUrl=true
                zipStoreBase=GRADLE_USER_HOME
                zipStorePath=wrapper/dists
                """);
        Path targetJar = root.resolve("gradle/wrapper/gradle-wrapper.jar");
        Files.createDirectories(targetJar.getParent());
        if (Files.notExists(targetJar)) {
            Files.copy(wrapperJar, targetJar);
        } else if (!Files.isRegularFile(targetJar, LinkOption.NOFOLLOW_LINKS)
                || Files.mismatch(wrapperJar, targetJar) != -1L) {
            throw new IOException("existing Gradle wrapper JAR differs from the verified fixture input");
        }
        write(root.resolve("src/main/kotlin/acceptance/Main.kt"), healthy ? """
                package acceptance

                import com.sun.net.httpserver.HttpServer
                import java.net.InetSocketAddress

                fun main() {
                    val server = HttpServer.create(InetSocketAddress("0.0.0.0", System.getenv("PORT").toInt()), 0)
                    server.createContext("/") { exchange ->
                        val body = "%s".toByteArray()
                        exchange.sendResponseHeaders(200, body.size.toLong())
                        exchange.responseBody.use { it.write(body) }
                    }
                    server.start()
                }
                """.formatted(marker) : "package acceptance\nfun main() { kotlin.system.exitProcess(36) }\n");
    }

    private static void php(Path root, String version, String marker, boolean healthy) throws IOException {
        write(root.resolve("composer.json"), """
                {
                  "name": "windowstolinux/acceptance",
                  "require": {},
                  "config": {
                    "platform": { "php": "%s" },
                    "sort-packages": true
                  }
                }
                """.formatted(version));
        write(root.resolve("composer.lock"), """
                {
                  "_readme": ["Generated for WindowsToLinux acceptance."],
                  "content-hash": "d41d8cd98f00b204e9800998ecf8427e",
                  "packages": [],
                  "packages-dev": [],
                  "aliases": [],
                  "minimum-stability": "stable",
                  "stability-flags": {},
                  "prefer-stable": false,
                  "prefer-lowest": false,
                  "platform": {},
                  "platform-dev": {},
                  "plugin-api-version": "2.6.0"
                }
                """);
        write(root.resolve("public/index.php"), healthy ? """
                <?php
                require dirname(__DIR__) . '/vendor/autoload.php';
                header('Content-Type: text/plain');
                echo '%s';
                """.formatted(marker) : "<?php http_response_code(503); echo 'unhealthy';\n");
    }

    private static void ruby(Path root, String version, String marker, boolean healthy) throws IOException {
        write(root.resolve(".ruby-version"), version + "\n");
        write(root.resolve("Gemfile"), """
                source "https://rubygems.org"
                gem "rack", "2.2.9"
                gem "webrick", "1.8.1"
                """);
        write(root.resolve("Gemfile.lock"), """
                GEM
                  remote: https://rubygems.org/
                  specs:
                    rack (2.2.9)
                    webrick (1.8.1)

                PLATFORMS
                  ruby

                DEPENDENCIES
                  rack (= 2.2.9)
                  webrick (= 1.8.1)

                BUNDLED WITH
                   2.4.22
                """);
        write(root.resolve("config.ru"), healthy
                ? "run ->(_env) { [200, {\"content-type\" => \"text/plain\"}, [\"" + marker + "\"]] }\n"
                : "exit 36\n");
    }

    private static void write(Path path, String value) throws IOException {
        Files.createDirectories(path.getParent());
        Files.writeString(path, value, StandardCharsets.UTF_8);
    }
}
