<script setup lang="ts">
import { onMounted,ref,watch } from 'vue'
import { request,submitTask,type ServerProfile } from '../../shared/api/client'
import type { ApplicationProfile } from '../application/ApplicationsPage.vue'
import { t,errorText } from '../../shared/i18n/messages'
import AppIcon from '../../shared/ui/AppIcon.vue'
interface BackupProfile {id:string;name:string;byteCount:number;createdAt:string;digest:string;inspection:{application:string;components:number;database:string;canRestore:boolean;provenance:string}}
const props=defineProps<{active:boolean}>(),emit=defineEmits<{task:[id:string]}>()
const backups=ref<BackupProfile[]>([]),applications=ref<ApplicationProfile[]>([]),servers=ref<ServerProfile[]>([]),application=ref(''),backup=ref(''),target=ref(''),mode=ref('create'),error=ref(''),busy=ref(false),uploadInput=ref<HTMLInputElement>()
async function load(){try{[backups.value,applications.value,servers.value]=await Promise.all([request<BackupProfile[]>('backups'),request<ApplicationProfile[]>('applications'),request<ServerProfile[]>('servers')]);error.value=''}catch(e){error.value=errorText(e)}}
async function run(kind:string){busy.value=true;try{let input:unknown=kind==='BACKUP_CREATE'?{applicationId:application.value}:kind==='MIGRATE'?{applicationId:application.value,targetServerId:target.value}:{backupId:backup.value,serverId:target.value};emit('task',(await submitTask(kind,input)).id)}catch(e){error.value=errorText(e)}finally{busy.value=false}}
async function upload(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;busy.value=true;try{const name=file.name.replace(/[^A-Za-z0-9_.-]/g,'-').slice(0,100);const saved=await request<BackupProfile>(`backups/upload?name=${encodeURIComponent(name)}`,'PUT',file);backup.value=saved.id;mode.value='restore';await load()}catch(e){error.value=errorText(e)}finally{busy.value=false;if(uploadInput.value)uploadInput.value.value=''}}
watch(()=>props.active,active=>{if(active)void load()});onMounted(load)
</script>
<template><section><header class="page-heading"><div><p class="eyebrow">BACKUP & RECOVERY</p><h1>{{t('backup')}}</h1><p>{{t('backupHint')}}</p></div><button :disabled="busy" @click="uploadInput?.click()"><AppIcon name="plus"/>{{t('importBackup')}}</button><input ref="uploadInput" class="visually-hidden" type="file" accept=".zip" @change="upload"/></header><p v-if="error" class="error" role="alert">{{error}}</p>
  <div class="panel"><div class="segmented"><button v-for="item in ['create','restore','migrate']" :key="item" :class="{selected:mode===item}" @click="mode=item">{{t(item+'Backup')}}</button></div>
    <label v-if="mode!=='restore'">{{t('applications')}}<select v-model="application"><option value="">{{t('selectApplication')}}</option><option v-for="app in applications.filter(a=>a.kind==='MANAGED')" :key="app.id" :value="app.id">{{app.name}} · {{servers.find(s=>s.id===app.serverId)?.name}}</option></select></label>
    <label v-else>{{t('backupArchive')}}<select v-model="backup"><option value="">{{t('selectBackup')}}</option><option v-for="item in backups" :key="item.id" :value="item.id" :disabled="!item.inspection.canRestore">{{item.name}} · {{new Date(item.createdAt).toLocaleString()}}</option></select></label>
    <label v-if="mode!=='create'">{{t('targetServer')}}<select v-model="target"><option value="">{{t('selectServer')}}</option><option v-for="server in servers" :key="server.id" :value="server.id" :disabled="mode==='migrate'&&applications.find(a=>a.id===application)?.serverId===server.id">{{server.name}} · {{server.host}}</option></select></label>
    <p class="help">{{t(mode==='migrate'?'migrationHint':mode==='restore'?'restoreHint':'createBackupHint')}}</p><div class="button-row"><button v-if="mode==='restore'" :disabled="!backup||!target||busy" @click="run('RESTORE_PREFLIGHT')">{{t('preflight')}}</button><button class="primary" :disabled="busy||(mode==='create'?!application:mode==='restore'?(!backup||!target):(!application||!target))" @click="run(mode==='create'?'BACKUP_CREATE':mode==='restore'?'RESTORE':'MIGRATE')">{{t(mode+'Backup')}}</button></div>
  </div><div class="section-heading"><h2>{{t('savedBackups')}}</h2><button @click="load">{{t('refresh')}}</button></div><p v-if="!backups.length" class="empty">{{t('noBackups')}}</p><div class="card-grid"><article v-for="item in backups" :key="item.id" class="resource-card"><div class="card-heading"><span class="icon-tile"><AppIcon name="backup"/></span><div><h2>{{item.name}}</h2><p>{{new Date(item.createdAt).toLocaleString()}}</p></div></div><p>{{item.inspection.components}} {{t('components')}} · {{(item.byteCount/1048576).toFixed(1)}} MiB · {{item.inspection.database}}</p><span class="status-badge">{{t(item.inspection.canRestore?'restoreReady':'inspectOnly')}}</span><p class="help break mono">SHA-256 {{item.digest}}</p><footer><a class="button" :href="`/api/v1/backups/${item.id}/download`" download>{{t('download')}}</a><button :disabled="!item.inspection.canRestore" @click="backup=item.id;mode='restore'">{{t('restoreBackup')}}</button></footer></article></div>
</section></template>
