package gold.debug.wtlweb.controller;

import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;

@RestController
@RequestMapping("/api/download")
public class DownloadController {

    private static final List<String> ALLOWED_FORMATS = Arrays.asList("exe", "msi", "zip", "jar");

    @GetMapping("/{format}")
    public ResponseEntity<Resource> downloadFile(@PathVariable String format) {
        if (!ALLOWED_FORMATS.contains(format.toLowerCase())) {
            return ResponseEntity.badRequest().build();
        }

        String filename = "dlprojx-v2.4.0." + format;
        String dummyContent = "This is a dummy " + format + " file generated by DlProjX. Geek Terminal Download!";
        byte[] data = dummyContent.getBytes(StandardCharsets.UTF_8);
        ByteArrayResource resource = new ByteArrayResource(data);

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + filename + "\"")
                .contentLength(data.length)
                .contentType(MediaType.APPLICATION_OCTET_STREAM)
                .body(resource);
    }
}
